config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :doctors
  end
  namespace :admin do
    resources :hospitals
  end
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :practices, class_name: 'DoctorPractice', foreign_key: 'doctor_id'
  has_many :hospitals, through: :practices

  validates_presence_of :name

  def hospital_names
    hospitals.map(&:name).join(', ')
  end
end

app/models/doctor_practice.rb
class DoctorPractice < ApplicationRecord
  belongs_to :doctor
  belongs_to :hospital
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :practices, class_name: 'DoctorPractice', foreign_key: 'hospital_id'
  has_many :doctors, through: :practices

  validates_presence_of :name

  def doctor_names
    doctors.map(&:name).join(', ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.image = auth.info.image
      user.provider = auth.provider
      user.uid = auth.uid
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.google_oauth2'] && session['devise.google_oauth2_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/admin/doctors_controller.rb
class Admin::DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /admin/doctors
  # GET /admin/doctors.json
  def index
    @doctors = Doctor.includes(:hospitals).all
  end

  # GET /admin/doctors/1
  # GET /admin/doctors/1.json
  def show
  end

  # GET /admin/doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /admin/doctors/1/edit
  def edit
  end

  # POST /admin/doctors
  # POST /admin/doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to admin_doctor_url(@doctor), notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/doctors/1
  # PATCH/PUT /admin/doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to admin_doctor_url(@doctor), notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/doctors/1
  # DELETE /admin/doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to admin_doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, hospital_ids: [])
    end
end

app/controllers/admin/hospitals_controller.rb
class Admin::HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]

  # GET /admin/hospitals
  # GET /admin/hospitals.json
  def index
    @hospitals = Hospital.includes(:doctors).all
  end

  # GET /admin/hospitals/1
  # GET /admin/hospitals/1.json
  def show
  end

  # GET /admin/hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /admin/hospitals/1/edit
  def edit
  end

  # POST /admin/hospitals
  # POST /admin/hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)

    respond_to do |format|
      if @hospital.save
        format.html { redirect_to admin_hospital_url(@hospital), notice: 'Hospital was successfully created.' }
        format.json { render :show, status: :created, location: @hospital }
      else
        format.html { render :new }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/hospitals/1
  # PATCH/PUT /admin/hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to admin_hospital_url(@hospital), notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/hospitals/1
  # DELETE /admin/hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to admin_hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hospital_params
      params.require(:hospital).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_oauth2_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
  def doctor_form_url(doctor)
    doctor.persisted? ? admin_doctor_path(doctor) : admin_doctors_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospital_helper.rb
module HospitalHelper
  def hospital_form_url(hospital)
    hospital.persisted? ? admin_hospital_path(hospital) : admin_hospitals_path
  end
end

app/views/admin/doctors/_form.html.erb
<%= form_with(model: doctor, local: true, url: doctor_form_url(doctor)) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hospitals %>
    <%= form.collection_check_boxes :hospital_ids, Hospital.all, :id, :name do |h| %>
      <div class="collection-check-box">
        <%= h.check_box %>
        <%= h.label %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', admin_doctor_path(@doctor) %> |
<%= link_to 'Back', admin_doctors_path %>

app/views/admin/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hospitals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.hospital_names %></td>
        <td><%= link_to 'Show', admin_doctor_path(doctor) %></td>
        <td><%= link_to 'Edit', edit_admin_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', admin_doctor_path(doctor), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_admin_doctor_path %>

app/views/admin/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', admin_doctors_path %>

app/views/admin/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>
<p>
  <strong>Hospitals:</strong>
  <%= @doctor.hospital_names %>
</p>

<%= link_to 'Edit', edit_admin_doctor_path(@doctor) %> |
<%= link_to 'Back', admin_doctors_path %>

app/views/admin/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true, url: hospital_form_url(hospital)) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
        <% hospital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/hospitals/edit.html.erb
<h1>Editing Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', admin_hospital_path(@hospital) %> |
<%= link_to 'Back', admin_hospitals_path %>

app/views/admin/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Doctors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.name %></td>
        <td><%= hospital.doctor_names %></td>
        <td><%= link_to 'Show', admin_hospital_path(hospital) %></td>
        <td><%= link_to 'Edit', edit_admin_hospital_path(hospital) %></td>
        <td><%= link_to 'Destroy', admin_hospital_path(hospital), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hospital', new_admin_hospital_path %>

app/views/admin/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', admin_hospitals_path %>

app/views/admin/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hospital.name %>
</p>
<p>
  <strong>Doctors:</strong>
  <%= @hospital.doctor_names %>
</p>

<%= link_to 'Edit', edit_admin_hospital_path(@hospital) %> |
<%= link_to 'Back', admin_hospitals_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<% if current_user %>
  <h3><%= current_user.name %></h3>
  <h3><%= current_user.email %></h3>
  <%= image_tag(current_user.image) unless current_user.image.nil? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPersonalMd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
    <%= yield %>
  </body>
</html>